# Generated by Django 4.2.1 on 2025-05-11 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_category_todoitementity_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitementity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
